package com.migc.qatar2022.ui.theme

import androidx.compose.ui.unit.dp

val SMALL_ROUND_CORNER = 4.dp
val MEDIUM_ROUND_CORNER = 8.dp
val EXTRA_LARGE_ROUND_CORNER = 24.dp

val MEDIUM_HORIZONTAL_GAP = 12.dp
val SMALL_VERTICAL_GAP = 4.dp
val MEDIUM_VERTICAL_GAP = 12.dp

val SMALL_ELEVATION = 4.dp
val LARGE_ELEVATION = 12.dp

val EXTRA_SMALL_PADDING = 1.dp
val EXTRA_SMALL_HORIZONTAL_PADDING = 2.dp
val SMALL_HORIZONTAL_PADDING = 4.dp
val EXTRA_SMALL_VERTICAL_PADDING = 2.dp
val SMALL_VERTICAL_PADDING = 4.dp
val MEDIUM_VERTICAL_PADDING = 8.dp
val SMALL_PADDING = 4.dp
val MEDIUM_PADDING = 8.dp
val LARGE_PADDING = 16.dp
val EXTRA_LARGE_PADDING = 24.dp
val BOTTOM_LIST_SPACE = 64.dp

val GROUP_LAZY_ROW_HEIGHT = 296.dp
val FLAG_ROW_IMAGE_SIZE = 36.dp
val SCORE_TEXT_FIELD_WIDTH = 50.dp

val DIALOG_WIDTH = 384.dp

val BOTTOM_SHEET_ROW_HEIGHT = 52.dp
val BOTTOM_SHEET_HEIGHT = 0.dp
val HANDLE_WIDTH = 48.dp
val HANDLE_HEIGHT = 6.dp
val HANDLE_ROUNDED_CORNER = 25.dp

val FIRST_PLACE_PODIUM_HEIGHT = 144.dp
val SECOND_PLACE_PODIUM_HEIGHT = 120.dp
val THIRD_PLACE_PODIUM_HEIGHT = 96.dp
val PODIUM_WIDTH = 72.dp
val PODIUM_STAMP_SIZE = 36.dp

val MEDIUM_BUTTON_HEIGHT = 52.dp
val LARGE_BUTTON_WIDTH = 256.dp
val GROUP_CARD_SIZE = 296.dp
val KNOCK_OUT_GRID_WIDTH = 640.dp
val KNOCK_OUT_GRID_HEIGHT = 384.dp
val GRID_TOP_GAP_PHASE_5 = FLAG_ROW_IMAGE_SIZE + (MEDIUM_VERTICAL_GAP / 2) + (EXTRA_SMALL_PADDING * 2)
val GRID_MID_GAP_PHASE_5 = (MEDIUM_VERTICAL_GAP * 2) + (FLAG_ROW_IMAGE_SIZE * 2) + (EXTRA_SMALL_PADDING * 5)

val PREDICTIONS_BUTTON_HEIGHT = 42.dp
val COIN_SIZE = 76.dp
val COIN_BORDER_STROKE = 2.dp

val SMALL_CIRCULAR_PROGRESS_SIZE = 36.dp

val STARS_SPACE_BETWEEN = 4.dp

val TOP_TEAMS_DISPLAY_HEIGHT = 196.dp
val TOP_TEAMS_DISPLAY_WIDTH = 148.dp
val TOP_TEAMS_DISPLAY_TITLE_HEIGHT = 20.dp