package com.migc.qatar2022.ui.theme

import androidx.compose.ui.unit.dp

val SMALL_ROUND_CORNER = 4.dp
val MEDIUM_ROUND_CORNER = 8.dp

val SMALL_HORIZONTAL_GAP = 4.dp
val MEDIUM_HORIZONTAL_GAP = 12.dp
val SMALL_VERTICAL_GAP = 4.dp
val MEDIUM_VERTICAL_GAP = 12.dp

val SMALL_ELEVATION = 4.dp

val EXTRA_SMALL_HORIZONTAL_PADDING = 2.dp
val SMALL_HORIZONTAL_PADDING = 4.dp
val EXTRA_SMALL_VERTICAL_PADDING = 2.dp
val SMALL_VERTICAL_PADDING = 4.dp
val MEDIUM_VERTICAL_PADDING = 8.dp
val SMALL_PADDING = 4.dp
val MEDIUM_PADDING = 8.dp
val LARGE_PADDING = 16.dp
val EXTRA_LARGE_PADDING = 24.dp

val GROUP_LAZY_ROW_HEIGHT = 296.dp
val FLAG_ROW_IMAGE_SIZE = 36.dp